name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/111485640684/locations/global/workloadIdentityPools/github-actions-gradle/providers/github-actions-gradle'
        service_account: 'gridasov@artifact-registry-vpcsc-test.iam.gserviceaccount.com'
    - name: Upload to Artifact Registry
      run: |
        gradle publish